device: "Tesla V100-SXM2-16GB" #Useless info

base:
  name: "OpenSLUv1"
  train: True
  test: True
  device: cuda
  seed: 42
  epoch_num: 150
  batch_size: 32

model_manager:
  load_dir: null
  save_dir: save/roberta-atis

evaluator:
  best_key: EMA
  eval_by_epoch: true
  # eval_step: 1800
  metric:
    - intent_acc
    - slot_f1
    - EMA

accelerator:
  use_accelerator: false

dataset:
  dataset_name: atis

tokenizer:
  _tokenizer_name_: roberta-base
  _padding_side_: right
  add_special_tokens: true
  max_length: 50

optimizer:
  _model_target_: torch.optim.AdamW
  _model_partial_: true
  lr: 2e-5
  weight_decay: 1e-8

scheduler:
  _model_target_: transformers.get_scheduler
  _model_partial_: true
  name : "linear"
  num_warmup_steps: 0

model:
  _model_target_: model.open_slu_model.OpenSLUModel
  ignore_index: -100
  encoder:
    _model_target_: model.encoder.AutoEncoder
    encoder_name: roberta-base
    output_dim: 768
    return_with_input: true
    return_sentence_level_hidden: true
  
      #decoder:
      #_model_target_: model.decoder.DCANetDecoder
      #interaction:
      #_model_target_: model.decoder.interaction.DCANetInteraction
      #output_dim: 768
      #attention_dropout: 0.5
      #num_attention_heads: 8

      #intent_classifier:
      #_model_target_: model.decoder.classifier.LinearClassifier
      #mode: "intent"
      #input_dim: 768
      #ignore_index: -100

      #slot_classifier:
      #_model_target_: model.decoder.classifier.LinearClassifier
      #mode: "slot"
      #input_dim: 768
      #ignore_index: -100

  decoder:
    _model_target_: model.decoder.BaseDecoder

    interaction:
      _model_target_: model.decoder.interaction.SlotGatedInteraction
      remove_slot_attn: false
      output_dim: 768
      dropout_rate: 0.4

    intent_classifier:
      _model_target_: model.decoder.classifier.LinearClassifier
      mode: "intent"
      ignore_index: -100

    slot_classifier:
      _model_target_: model.decoder.classifier.LinearClassifier
      mode: "slot"
      ignore_index: -100

  #decoder:
  #  _model_target_: model.decoder.new_decoder.NewDecoder #model.decoder.base_decoder.BaseDecoder

        #  interaction:
        #_model_target_: model.decoder.interaction.new_interaction.NewInteraction #base_interaction.BaseInteraction
        #hidden_dim: 768
        #output_dim: 768
        #dropout_rate: 0.1

        #intent_classifier:
        #_model_target_: model.decoder.classifier.LinearClassifier
        #mode: "intent"
        #ignore_index: -100


        #slot_classifier:
        #_model_target_: model.decoder.classifier.LinearClassifier
        #mode: "slot"
        #ignore_index: -100
